version: '3.8'

services:
  new_backend:
    build: ./backend
    container_name: new_backend
    restart: unless-stopped
    ports:
      - "8001:8000"  # Different from first app
    networks:
      - new_app_network

  new_frontend:
    build: ./frontend
    container_name: new_frontend
    restart: unless-stopped
    ports:
      - "3001:3000"  # Different from first app
    depends_on:
      - new_backend
    networks:
      - new_app_network

  new_nginx:
    build: ./nginx
    container_name: new_nginx
    restart: unless-stopped
    ports:
      - "8081:80"  # Different from first app
    depends_on:
      - new_frontend
    networks:
      - new_app_network
    volumes:
      - /etc/ssl/certs/fullchain.pem:/etc/ssl/certs/fullchain.pem
      - /etc/ssl/private/bot-ai.key:/etc/ssl/private/bot-ai.key

networks:
  new_app_network:
    driver: bridge
