version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: hamshackbuddy-backend
    restart: unless-stopped
    env_file:
      - ./backend/.env
    ports:
      - "8001:8001"
    networks:
      - hamshackbuddy-network
      - nginx-network  # Connect to existing nginx network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: hamshackbuddy-frontend
    restart: unless-stopped
    ports:
      - "3001:3000"
    depends_on:
      - backend
    networks:
      - hamshackbuddy-network
      - nginx-network  # Connect to existing nginx network

networks:
  hamshackbuddy-network:
    driver: bridge
  nginx-network:
    external: true  # Use existing network that nginx is already on